# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
org.gradle.parallel=true
org.gradle.workers.max=1

# 设置 Gradle 用户目录到 D 盘，避免中文路径问题
org.gradle.user.home=D:/gradle-cache

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.18.4
loom_version=1.9-SNAPSHOT

# Mod Properties
mod_version=0.1.0+1.21
maven_group=com.nutonmod
archives_base_name=nutonmod

# Dependencies
fabric_api_version=0.102.0+1.21
geckolib_version=4.5.8
