package com.nutonmod.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModENUSLanProvider extends FabricLanguageProvider {
    public ModENUSLanProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, "en_us", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add("item.nutonmod.energy_core", "Energy Core");
        translationBuilder.add("block.nutonmod.energy_core", "Energy Core");
        translationBuilder.add("block.nutonmod.energy_block", "Energy Block");
        translationBuilder.add("item.nutonmod.energy_being_spawn_egg", "Energy Being Spawn Egg");
        translationBuilder.add("item.nutonmod.energy_sprite_spawn_egg", "Energy Sprite Spawn Egg");
        translationBuilder.add("item.nutonmod.crystal_snail_spawn_egg", "Crystal Snail Spawn Egg");
        translationBuilder.add("item.nutonmod.storm_finch_spawn_egg", "Storm Finch Spawn Egg");
        translationBuilder.add("item.nutonmod.energy_warden_spawn_egg", "Energy Warden Spawn Egg");
        translationBuilder.add("item.nutonmod.void_crawler_spawn_egg", "Void Crawler Spawn Egg");
        translationBuilder.add("item.nutonmod.storm_elemental_spawn_egg", "Storm Elemental Spawn Egg");
        translationBuilder.add("item.nutonmod.holy_helmet", "Holy Helmet");
        translationBuilder.add("item.nutonmod.holy_chestplate", "Holy Chestplate");
        translationBuilder.add("item.nutonmod.holy_leggings", "Holy Leggings");
        translationBuilder.add("item.nutonmod.holy_boots", "Holy Boots");
        translationBuilder.add("item.nutonmod.energy_apple", "Energy Apple");
        translationBuilder.add("item.nutonmod.energy_potato", "Energy Potato");
        translationBuilder.add("item.nutonmod.anthracite", "Anthracite");
        translationBuilder.add("item.nutonmod.anthracite_block", "Anthracite Block");
        translationBuilder.add("block.nutonmod.anthracite_block", "Anthracite Block");
        translationBuilder.add("item.nutonmod.prospector", "Prospector");
        translationBuilder.add("item.nutonmod.test_music_disc", "Test Music Disc");

        translationBuilder.add("block.nutonmod.energy_stairs", "Energy Stairs");
        translationBuilder.add("block.nutonmod.energy_slab", "Energy Slab");
        translationBuilder.add("block.nutonmod.energy_button", "Energy Button");
        translationBuilder.add("block.nutonmod.energy_pressure_plate", "Energy Pressure Plate");
        translationBuilder.add("block.nutonmod.stabilizer_beacon", "Stabilizer Beacon");
        translationBuilder.add("block.nutonmod.energy_fence", "Energy Fence");
        translationBuilder.add("block.nutonmod.energy_fence_gate", "Energy Fence Gate");
        translationBuilder.add("block.nutonmod.energy_wall", "Energy Wall");
        translationBuilder.add("block.nutonmod.energy_door", "Energy Door");
        translationBuilder.add("block.nutonmod.energy_trapdoor", "Energy Trapdoor");

        translationBuilder.add("item.nutonmod.energy_sword", "Energy Sword");
        translationBuilder.add("item.nutonmod.energy_pickaxe", "Energy Pickaxe");
        translationBuilder.add("item.nutonmod.energy_axe", "Energy Axe");
        translationBuilder.add("item.nutonmod.energy_shovel", "Energy Shovel");
        translationBuilder.add("item.nutonmod.energy_hoe", "Energy Hoe");
        translationBuilder.add("item.nutonmod.energy_ingot", "Energy Ingot");
        translationBuilder.add("item.nutonmod.raw_energy", "Raw Energy");
        translationBuilder.add("item.nutonmod.altar_shard", "Altar Shard");
        translationBuilder.add("item.nutonmod.core_stabilizer", "Core Stabilizer");
        translationBuilder.add("item.nutonmod.storm_fragment", "Storm Fragment");
        translationBuilder.add("item.nutonmod.storm_alloy", "Storm Alloy");
        translationBuilder.add("item.nutonmod.crystal_matrix", "Crystal Matrix");
        translationBuilder.add("item.nutonmod.sanctum_key", "Sanctum Key");
        translationBuilder.add("item.nutonmod.core_heart", "Core Heart");
        translationBuilder.add("item.nutonmod.annihilation_eye", "Eye of Annihilation");
        translationBuilder.add("item.nutonmod.annihilation_core", "Annihilation Core");
        translationBuilder.add("item.nutonmod.singularity_shard", "Singularity Shard");
        translationBuilder.add("item.nutonmod.energy_essence", "Energy Essence");
        translationBuilder.add("item.nutonmod.energy_crystal", "Energy Crystal");
        translationBuilder.add("item.nutonmod.tuning_essence", "Tuning Essence");
        translationBuilder.add("item.nutonmod.sprite_dust", "Sprite Dust");
        translationBuilder.add("item.nutonmod.crystal_shard", "Crystal Shard");
        translationBuilder.add("item.nutonmod.snail_shell", "Snail Shell");
        translationBuilder.add("item.nutonmod.crystal_snail_capsule", "Crystal Snail Capsule");
        translationBuilder.add("item.nutonmod.storm_feather", "Storm Feather");
        translationBuilder.add("item.nutonmod.storm_seed", "Storm Seed");
        translationBuilder.add("item.nutonmod.warden_core", "Warden Core");
        translationBuilder.add("item.nutonmod.void_silk", "Void Silk");
        translationBuilder.add("item.nutonmod.void_slime_ball", "Void Slime Ball");
        translationBuilder.add("item.nutonmod.storm_essence", "Storm Essence");
        translationBuilder.add("item.nutonmod.storm_core", "Storm Core");
        translationBuilder.add("item.nutonmod.crystal_helmet", "Crystal Helmet");
        translationBuilder.add("item.nutonmod.storm_charm", "Storm Charm");
        translationBuilder.add("item.nutonmod.annihilation_blade", "Annihilation Blade");
        translationBuilder.add("item.nutonmod.arbiter_sigil", "Arbiter Sigil");
        translationBuilder.add("item.nutonmod.thunderforged_core", "Thunderforged Core");
        translationBuilder.add("item.nutonmod.lightning_essence", "Lightning Essence");
        translationBuilder.add("item.nutonmod.arbiter_trophy", "Arbiter Trophy");
        translationBuilder.add("item.nutonmod.thunder_spear", "Thunder Spear");
        translationBuilder.add("item.nutonmod.thunder_ripper", "Thunder Ripper");
        translationBuilder.add("item.nutonmod.void_calamity", "Void Calamity");
        translationBuilder.add("item.nutonmod.storm_scepter", "Storm Scepter");
        translationBuilder.add("item.nutonmod.archon_mark", "Archon Mark");
        translationBuilder.add("item.nutonmod.end_heart", "Heart of End");
        translationBuilder.add("item.nutonmod.void_fragment", "Void Fragment");
        translationBuilder.add("item.nutonmod.end_tome", "Codex of End");
        translationBuilder.add("item.nutonmod.void_wings", "Void Wings");
        translationBuilder.add("item.nutonmod.end_judicator", "End Judicator");
        translationBuilder.add("tooltip.nutonmod.annihilation_blade.line1", "Active: Right click releases Annihilation Slash");
        translationBuilder.add("tooltip.nutonmod.annihilation_blade.line2", "Passive: hits stack marks, max stacks trigger execute pulse");
        translationBuilder.add("tooltip.nutonmod.annihilation_blade.line3", "On kill: restores health");
        translationBuilder.add("tooltip.nutonmod.thunder_spear.line1", "Right click: throw and return lightning spear");
        translationBuilder.add("tooltip.nutonmod.thunder_spear.line2", "Impact: splash shock + short chain lightning");
        translationBuilder.add("tooltip.nutonmod.thunder_spear.line3", "On kill: grants short Strength");
        translationBuilder.add("tooltip.nutonmod.thunder_ripper.line1", "Sweep: hit up to 3 enemies in 180 degrees");
        translationBuilder.add("tooltip.nutonmod.thunder_ripper.line2", "30% chain lightning (50% in storms), 6 hearts chain hit");
        translationBuilder.add("tooltip.nutonmod.thunder_ripper.line3", "Right click: 1.2s lightning spin, pull + multi-hit, ends with chain burst");
        translationBuilder.add("tooltip.nutonmod.thunder_ripper.line4", "Storm: +30% attack speed, +chain chance, half skill cooldown");
        translationBuilder.add("tooltip.nutonmod.void_calamity.line1", "Bow with Void Charge and Annihilation Shot");
        translationBuilder.add("tooltip.nutonmod.void_calamity.line2", "Sneak + right click: consume 3 charges to create mini black hole");
        translationBuilder.add("tooltip.nutonmod.void_calamity.line3", "Kills grant charges (up to 5), arrows can truly pierce");
        translationBuilder.add("tooltip.nutonmod.storm_scepter.line1", "Right click: chain lightning (costs energy)");
        translationBuilder.add("tooltip.nutonmod.storm_scepter.line2", "Sneak + right click: Storm Eye area control");
        translationBuilder.add("tooltip.nutonmod.storm_scepter.line3", "Overload in storms: no energy cost and bonus damage");
        translationBuilder.add("tooltip.nutonmod.end_judicator.line1", "Sneak + right click: switch form");
        translationBuilder.add("tooltip.nutonmod.end_judicator.line2", "Power Form: close-range annihilation blast");
        translationBuilder.add("tooltip.nutonmod.end_judicator.line3", "Agile Form: long-range void slash");
        translationBuilder.add("item.nutonmod.end_judicator.mode_power", "Switched to Power Form");
        translationBuilder.add("item.nutonmod.end_judicator.mode_agile", "Switched to Agile Form");
        translationBuilder.add("item.nutonmod.end_judicator.current_power", "Current Form: Power");
        translationBuilder.add("item.nutonmod.end_judicator.current_agile", "Current Form: Agile");
        translationBuilder.add("item.nutonmod.end_tome.unlocked", "Hidden end recipes unlocked");
        translationBuilder.add("item.nutonmod.end_tome.unlocked_list", "Unlocked: End Judicator");
        translationBuilder.add("weapon.nutonmod.end_judicator.need_energy", "Not enough energy: need %s");
        translationBuilder.add("item.nutonmod.void_wings.need_wear", "Equip Void Wings in chest slot first");
        translationBuilder.add("item.nutonmod.void_wings.dimension_only", "Can only activate in the Energy Realm");
        translationBuilder.add("item.nutonmod.void_wings.flight_ready", "Void Wings activated: 5s flight");
        translationBuilder.add("item.nutonmod.void_wings.flight_hint", "Sneak mid-air to trigger Void Wings");
        translationBuilder.add("item.nutonmod.void_wings.flight_cd", "Void Wings cooling down: %s s");
        translationBuilder.add("item.nutonmod.void_wings.rescue_triggered", "Void Walk triggered: lethal damage negated");
        translationBuilder.add("weapon.nutonmod.void_calamity.need_charge", "Need at least 3 Void Charges");
        translationBuilder.add("weapon.nutonmod.void_calamity.charge", "Void Charge: %s/%s");
        translationBuilder.add("weapon.nutonmod.storm_scepter.need_energy_cast", "Not enough energy: need 15");
        translationBuilder.add("weapon.nutonmod.storm_scepter.need_energy_eye", "Not enough energy: need 40");
        translationBuilder.add("weapon.nutonmod.thunder_ripper.need_energy_hit", "Not enough energy: need 3");
        translationBuilder.add("weapon.nutonmod.thunder_ripper.need_energy_skill", "Not enough energy: need 20");
        translationBuilder.add("block.nutonmod.energy_ore", "Energy Ore");
        translationBuilder.add("block.nutonmod.deepslate_energy_ore", "Deepslate Energy Ore");

        translationBuilder.add("item.nutonmod.hat", "Hat");
        translationBuilder.add("entity.nutonmod.energy_being", "Energy Being");
        translationBuilder.add("entity.nutonmod.energy_being.stormborn", "Stormborn Energy Being");
        translationBuilder.add("entity.nutonmod.rift_stalker", "Rift Stalker");
        translationBuilder.add("entity.nutonmod.rift_stalker.storm", "Storm Rift Stalker");
        translationBuilder.add("entity.nutonmod.singularity", "Singularity of Annihilation");
        translationBuilder.add("entity.nutonmod.storm_arbiter", "Storm Arbiter, the Bolt-Forged");
        translationBuilder.add("entity.nutonmod.void_archon", "Void Archon, the Emissary of End");
        translationBuilder.add("entity.nutonmod.storm_guard", "Storm Guard");
        translationBuilder.add("entity.nutonmod.energy_sprite", "Energy Sprite");
        translationBuilder.add("entity.nutonmod.crystal_snail", "Crystal Snail");
        translationBuilder.add("entity.nutonmod.storm_finch", "Storm Finch");
        translationBuilder.add("entity.nutonmod.energy_warden", "Energy Warden");
        translationBuilder.add("entity.nutonmod.void_crawler", "Void Crawler");
        translationBuilder.add("entity.nutonmod.storm_elemental", "Storm Elemental");
        translationBuilder.add("boss.nutonmod.singularity.need_core_wastes", "Need to summon in Core Wastes biome");
        translationBuilder.add("boss.nutonmod.singularity.already_active", "A Singularity is already active nearby");
        translationBuilder.add("boss.nutonmod.singularity.awakened", "Singularity of Annihilation has awakened!");
        translationBuilder.add("boss.nutonmod.singularity.phase_2", "Core collapse begins!");
        translationBuilder.add("boss.nutonmod.singularity.phase_3", "Annihilation descends!");
        translationBuilder.add("boss.nutonmod.singularity.black_hole_warning", "Space is collapsing into a black hole!");
        translationBuilder.add("boss.nutonmod.singularity.nova_warning", "Annihilation nova is charging - find a shield anchor!");
        translationBuilder.add("boss.nutonmod.singularity.rampage_warning", "The Singularity is entering rampage charge!");
        translationBuilder.add("boss.nutonmod.singularity.mirror_warning", "The core splits - find the true Singularity!");
        translationBuilder.add("boss.nutonmod.singularity.decoy_name", "Singularity Phantom");
        translationBuilder.add("boss.nutonmod.singularity.bar.phase_1", "Singularity of Annihilation - Gravity Awakening");
        translationBuilder.add("boss.nutonmod.singularity.bar.phase_2", "Singularity of Annihilation - Core Collapse");
        translationBuilder.add("boss.nutonmod.singularity.bar.phase_3", "Singularity of Annihilation - Annihilation Descent");
        translationBuilder.add("boss.nutonmod.singularity.node_cooldown", "Energy node cooling down: %s s");
        translationBuilder.add("boss.nutonmod.singularity.node_red", "Red node activated: +50% attack power");
        translationBuilder.add("boss.nutonmod.singularity.node_blue", "Blue node activated: +50% movement speed");
        translationBuilder.add("boss.nutonmod.singularity.node_yellow", "Yellow node activated: +20 hearts healed");
        translationBuilder.add("boss.nutonmod.singularity.node_purple", "Purple node activated: +20 hearts absorption");
        translationBuilder.add("boss.nutonmod.singularity.boundary_warning", "The arena edge rejects you - return to the center!");
        translationBuilder.add("boss.nutonmod.storm_arbiter.awakened", "Storm Arbiter, the Bolt-Forged has descended!");
        translationBuilder.add("boss.nutonmod.storm_arbiter.need_storm_fields", "Must summon in Storm Fields biome");
        translationBuilder.add("boss.nutonmod.storm_arbiter.need_thunder", "Thunderstorm weather is required");
        translationBuilder.add("boss.nutonmod.storm_arbiter.already_active", "A Storm Arbiter is already active nearby");
        translationBuilder.add("boss.nutonmod.storm_arbiter.phase_2", "Bolt-Forged Wrath - Phase Two!");
        translationBuilder.add("boss.nutonmod.storm_arbiter.phase_3", "Avatar of Storm - Final Phase!");
        translationBuilder.add("boss.nutonmod.storm_arbiter.final_judgement", "Final Judgement: unavoidable strike in 5 seconds!");
        translationBuilder.add("boss.nutonmod.storm_arbiter.judgement_survived", "You endured the Final Judgement through sanctuary protection!");
        translationBuilder.add("boss.nutonmod.storm_arbiter.rod_cd", "Lightning rod pillar cooling down: %s s");
        translationBuilder.add("boss.nutonmod.storm_arbiter.bar.phase_1", "Storm Arbiter - Thunder Judgement");
        translationBuilder.add("boss.nutonmod.storm_arbiter.bar.phase_2", "Storm Arbiter - Bolt-Forged Wrath");
        translationBuilder.add("boss.nutonmod.storm_arbiter.bar.phase_3", "Storm Arbiter - Avatar of Storm");
        translationBuilder.add("boss.nutonmod.void_archon.need_core_wastes", "Must summon in Core Wastes biome");
        translationBuilder.add("boss.nutonmod.void_archon.need_prereq", "Defeat Singularity and Storm Arbiter first");
        translationBuilder.add("boss.nutonmod.void_archon.already_active", "A Void Archon is already active nearby");
        translationBuilder.add("boss.nutonmod.void_archon.awakened", "Void Archon, the Emissary of End has descended!");
        translationBuilder.add("boss.nutonmod.void_archon.phase_2", "Phase Shift: Cataclysm Claw!");
        translationBuilder.add("boss.nutonmod.void_archon.phase_3", "Phase Shift: Agile Void Form!");
        translationBuilder.add("boss.nutonmod.void_archon.phase_4", "Phase Shift: Endfall Manifest!");
        translationBuilder.add("boss.nutonmod.void_archon.final_judgement", "Final Judgement is charging!");
        translationBuilder.add("boss.nutonmod.void_archon.decoy_name", "Void Archon Mirror");
        translationBuilder.add("boss.nutonmod.void_archon.fragment_power", "Absorbed fragment: +Power");
        translationBuilder.add("boss.nutonmod.void_archon.fragment_speed", "Absorbed fragment: +Speed");
        translationBuilder.add("boss.nutonmod.void_archon.bar.phase_1", "Void Archon - Balanced Form");
        translationBuilder.add("boss.nutonmod.void_archon.bar.phase_2", "Void Archon - Power Form");
        translationBuilder.add("boss.nutonmod.void_archon.bar.phase_3", "Void Archon - Agile Form");
        translationBuilder.add("boss.nutonmod.void_archon.bar.phase_4", "Void Archon - End Form");
        translationBuilder.add("entity.minecraft.villager.energy_master", "Energy Master");
        translationBuilder.add("entity.minecraft.villager.nutonmod.energy_master", "Energy Master");

        translationBuilder.add("block.nutonmod.energy_potato_crop", "Energy Potato Crop");
        translationBuilder.add("item.nutonmod.corn_seeds", "Corn Seeds");
        translationBuilder.add("item.nutonmod.corn", "Corn");
        translationBuilder.add("sounds.nutonmod.prospector_found_ore", "Prospector Found Ore");
        translationBuilder.add("sounds.nutonmod.energy_block_break", "Energy Block Break");
        translationBuilder.add("sounds.nutonmod.energy_block_place", "Energy Block Place");
        translationBuilder.add("sounds.nutonmod.energy_block_hit", "Energy Block Hit");
        translationBuilder.add("sounds.nutonmod.energy_block_step", "Energy Block Step");
        translationBuilder.add("sounds.nutonmod.energy_block_fall", "Energy Block Fall");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_summon", "Storm Arbiter Summon");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_lightning_chain", "Storm Arbiter Lightning Chain");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_spear_throw", "Storm Arbiter Spear Throw");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_storm_cloud", "Storm Arbiter Storm Cloud");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_blade_storm", "Storm Arbiter Blade Storm");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_thunderfall", "Storm Arbiter Thunderfall");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_final_judgement", "Storm Arbiter Final Judgement");
        translationBuilder.add("sounds.nutonmod.storm_arbiter_death", "Storm Arbiter Death");
        translationBuilder.add("sounds.nutonmod.singularity_summon", "Singularity Summon");
        translationBuilder.add("sounds.nutonmod.singularity_phase_shift", "Singularity Phase Shift");
        translationBuilder.add("sounds.nutonmod.singularity_barrage", "Singularity Barrage");
        translationBuilder.add("sounds.nutonmod.singularity_gravity_well", "Singularity Gravity Well");
        translationBuilder.add("sounds.nutonmod.singularity_black_hole", "Singularity Black Hole");
        translationBuilder.add("sounds.nutonmod.singularity_rampage", "Singularity Rampage");
        translationBuilder.add("sounds.nutonmod.singularity_nova", "Singularity Nova");
        translationBuilder.add("sounds.nutonmod.singularity_death", "Singularity Death");
        translationBuilder.add("sounds.nutonmod.void_calamity_shot", "Void Calamity Shot");
        translationBuilder.add("sounds.nutonmod.void_calamity_annihilation", "Void Calamity Annihilation");
        translationBuilder.add("sounds.nutonmod.void_calamity_charge_full", "Void Calamity Charge Full");
        translationBuilder.add("sounds.nutonmod.storm_scepter_cast", "Storm Scepter Cast");
        translationBuilder.add("sounds.nutonmod.storm_scepter_eye", "Storm Scepter Eye");
        translationBuilder.add("sounds.nutonmod.storm_scepter_charge", "Storm Scepter Charge");
        translationBuilder.add("sounds.nutonmod.storm_scepter_arc", "Storm Scepter Arc");
        translationBuilder.add("sounds.nutonmod.storm_scepter_chain_impact", "Storm Scepter Chain Impact");
        translationBuilder.add("sounds.nutonmod.storm_scepter_eye_pulse", "Storm Scepter Eye Pulse");
        translationBuilder.add("sounds.nutonmod.thunder_spear_throw", "Thunder Spear Throw");
        translationBuilder.add("sounds.nutonmod.thunder_spear_return", "Thunder Spear Return");
        translationBuilder.add("sounds.nutonmod.thunder_ripper_swing", "Thunder Ripper Swing");
        translationBuilder.add("sounds.nutonmod.thunder_ripper_chain", "Thunder Ripper Chain");
        translationBuilder.add("sounds.nutonmod.thunder_ripper_dash", "Thunder Ripper Dash");
        translationBuilder.add("sounds.nutonmod.thunder_ripper_trail", "Thunder Ripper Trail");
        translationBuilder.add("sounds.nutonmod.thunder_ripper_impact", "Thunder Ripper Impact");

        translationBuilder.add("jukebox_song.nutonmod.test", "Test");
        translationBuilder.add("item.nutonmod.energy_bucket", "Energy Bucket");

        translationBuilder.add("item.nutonmod.energy_horse_armor", "Energy Horse Armor");
        translationBuilder.add("item.nutonmod.rift_stalker_spawn_egg", "Rift Stalker Spawn Egg");
        translationBuilder.add("item.nutonmod.singularity_spawn_egg", "Singularity Spawn Egg");
        translationBuilder.add("item.nutonmod.storm_arbiter_spawn_egg", "Storm Arbiter Spawn Egg");
        translationBuilder.add("item.nutonmod.void_archon_spawn_egg", "Void Archon Spawn Egg");

        translationBuilder.add("block.nutonmod.box", "Box");
        translationBuilder.add("item.nutonmod.box", "Box");
        translationBuilder.add("container.box", "Box");

        translationBuilder.add("block.nutonmod.polishing_machine", "Polishing Machine");
        translationBuilder.add("container.polishing_machine", "Polishing Machine");
        translationBuilder.add("gui.nutonmod.polishing_machine.status.ready", "Ready");
        translationBuilder.add("gui.nutonmod.polishing_machine.status.missing_material", "Missing Material");
        translationBuilder.add("gui.nutonmod.polishing_machine.status.output_full", "Output Full");
        translationBuilder.add("block.nutonmod.dimensional_tuner", "Dimensional Tuner");
        translationBuilder.add("item.nutonmod.dimensional_tuner", "Dimensional Tuner");
        translationBuilder.add("container.dimensional_tuner", "Dimensional Tuner");
        translationBuilder.add("block.nutonmod.energy_disintegrator", "Energy Disintegrator");
        translationBuilder.add("item.nutonmod.energy_disintegrator", "Energy Disintegrator");
        translationBuilder.add("container.energy_disintegrator", "Energy Disintegrator");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.button.start", "Disintegrate");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.current_mode", "Mode: %s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.energy", "Energy: %s/%s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.mode.equipment", "Equip");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.mode.boss", "Boss");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.mode.block", "Block");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.mode.essence", "Essence");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.status.idle", "Idle");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.status.ready", "Ready");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.status.running", "Disintegrating...");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.status.output_full", "Output Full");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.status.invalid_input", "Invalid input for mode");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.status.missing_energy", "Missing energy");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.button.switch", "Switch");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.current_status", "Status: %s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.recommended", "Recommend: %s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.empty", "Estimated: -");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.equipment_exact", "Estimated: %s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.equipment_exact_xp", "Estimated: %s, XP +%s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.boss", "Estimated: invalid boss material");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.boss_exact", "Estimated: success %s%% (%s), extra (%s), fail %s%%; %s guarantees success");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.boss_exact_guaranteed", "Estimated: success 100%% (%s), extra (%s); guaranteed by %s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.block", "Estimated: recipe refund");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.block_exact", "Estimated: %s");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.essence", "Estimated: Tuning Essence x1 + original gear");
        translationBuilder.add("gui.nutonmod.energy_disintegrator.preview.essence_exact", "Estimated: %s + %s");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.button.start", "Tune");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.button.assault", "Assault");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.button.guard", "Guard");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.button.mobility", "Move");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.current_mode", "Mode: %s");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.current_status", "Status: %s");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.mode.assault", "Assault");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.mode.guard", "Guard");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.mode.mobility", "Mobility");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.status.idle", "Idle");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.status.ready", "Ready");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.status.running", "Tuning...");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.status.output_full", "Output Full");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.status.invalid_tool", "Insert 1 damageable tool");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.status.invalid_catalyst", "Wrong catalyst for mode");
        translationBuilder.add("gui.nutonmod.dimensional_tuner.status.missing_energy", "Missing energy material");

        translationBuilder.add("block.nutonmod.energy_log", "Energy Log");
        translationBuilder.add("block.nutonmod.energy_wood", "Energy Wood");
        translationBuilder.add("block.nutonmod.stripped_energy_log", "Stripped Energy Log");
        translationBuilder.add("block.nutonmod.stripped_energy_wood", "Stripped Energy Wood");
        translationBuilder.add("block.nutonmod.energy_planks", "Energy Planks");
        translationBuilder.add("block.nutonmod.energy_leaves", "Energy Leaves");
        translationBuilder.add("block.nutonmod.energy_sapling", "Energy Sapling");
        translationBuilder.add("block.nutonmod.energy_flower", "Energy Flower");
        translationBuilder.add("block.nutonmod.potted_energy_flower", "Potted Energy Flower");
        translationBuilder.add("block.nutonmod.still_energy", "Still Energy");
        translationBuilder.add("biome.nutonmod.energy_biome", "Energy Biome");
    }
}
